name: Deploy Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Static Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List files for debugging
        run: |
          echo "Listing files in the src directory:"
          ls -R src

      - name: Install Dependencies
        run: npm install -g parcel

      - name: Build Project
        run: parcel build src/index.html # Ensure index.html exists in the src folder or update the path

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
